site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  code:
    highlight_theme: github
  palette:
    primary: "indigo"
    accent: "indigo"
  codehilite:
    guess_lang: false

nav:
  - Accueil: index.md
  - Fish shell: fish-shell/index.md
  - Git: git/index.md
  - MkDocs: mkdocs/index.md
  - Nvim: nvim/index.md
  - React:
      - React: react/index.md
      - Tanstack router: react/tanstack/tanstack-router.md
  - Biome: biome/index.md
