site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Language:
      - HTML: language/HTML/base.md
      - CSS: language/css/index.md 
      - Svelte: language/svelte/index.md
      - Hono: language/hono/index.md
      - C: language/c/index.md
      - Go: language/go/index.md
      - PHP: language/php/index.md
      - Python: language/python/index.md
      - JavaSscript:
          - JavaScript: language/javascript/index.md
          - Bun: language/bun/index.md
          - Elysia: language/elysia/index.md
      - React:
          - React: language/react/index.md
          - Tanstack Router: language/react/tanstack/tanstack-router.md
          - Tanstack Form: language/react/tanstack/tanstack-form.md
          - Tanstack Table: language/react/tanstack/tanstack-table.md
          - Tanstack Query: language/react/tanstack/tanstack-query.md
      - Express: language/express/index.md
      - SQL:
          - Introduction: language/sql/01-introduction
          - Instruction de base: language/sql/02-instruction_base.md
          - Postgres: language/sql/03-postgres.md
          - Formatage: language/sql/05_Formatage_des_donnees.md
          - Selection et trie: language/sql/06_selection_tri.md
          - Fonction d'agrégat: language/sql/07-regroupement-agregat.md
          - GROUP BY - HAVING: language/sql/08-utilisation-avancee-agregat.md
          - Travailler avec le NULL: language/sql/09-null.md
          - CASE - WHEN: language/sql/10-condition-avancee.md
          - Jointure: language/sql/11-jointure.md
          - Sous-requête: language/sql/12-sous-requete.md
          - Type SQL: language/sql/13-type-donnee.md
          - Tableau et JSON: language/sql/14-tableau-et-json
          - DB: language/sql/database.md
          - Conversion de type: language/sql/15-comparaison-et-conversion.md
          - Création et modification des tables: language/sql/16-creation-modification-table.md
          - Table temporaire: language/sql/17-table-temporaire.md
          - Clé étrangère et relations: language/sql/18-foreign-key-relation.md
          - Insertion, update et supression des données: language/sql/19-insertion-update-delete.md
          - Transaction: language/sql/20-transaction.md
          - Chargement de données en masse: language/sql/21-import-data.md
  - Outils:
      - Linux: tools/linux/index.md
      - Git: tools/git/index.md
      - Biome: tools/biome/index.md
      - Drizzle: tools/drizzle/index.md
      - Fish-Shell: tools/fish-shell/index.md
      - Mermaid: tools/mermaid/index.md
      - MkDocs: tools/mkdocs/index.md
      - Nvim: tools/nvim/index.md
      - Pnpm: tools/pnpm/index.md
      - Zod: tools/zod/index.md
  - Concept:
      - Gestion mémoire: concept/memory_managment.md
  - Evode:
      - Gestion des modales: evode/modale.md
      - Confirmation: evode/confirmation.md
