site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material

nav:
  - Accueil: index.md
  - Fish shell: fish-shell/index.md
  - Git: git/index.md
  - MkDocs: mkdocs/index.md
  - Nvim: nvim/index.md
