site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material

nav:
  - Accueil: index.md
  - Fish shell:
      - Introduction: fish-shell/index.md
      - Tips: fish-shell/tips.md
