site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Language: 
    - PHP: language/php/index.md 
    - Python: language/python/index.md 
    - SQL: 
      - Base de donnée: concept/database.md 
      - Instruction de base: language/sql/instruction_base.md 
      - DB: language/sql/database.md 
      - Postgres: language/sql/postgres.md
      - Formatage: language/sql/05_Formatage_des_donnees.md
      - Selection et trie: language/sql/06_selection_tri.md
      - Regroupement et agrégats: language/sql/07-regroupement-agregat.md
  - PHP: php/index.md
  - Pyhton: python/index.md
  - JavaSscript: javascript/index.md
  - React:
      - React: react/index.md
      - Tanstack Router: react/tanstack/tanstack-router.md
      - Tanstack Form: react/tanstack/tanstack-form.md
      - Tanstack Table: react/tanstack/tanstack-table.md 
      - Tanstack Query: react/tanstack/tanstack-query.md
  - Express: express/index.md
  - Base de données:
    - Base de donnée: db/index.md
    - SQL: sql/index.md
  - Git: git/index.md


