site_name: Engineering Handbook
site_url: https://engineering-handbook.netlify.app

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Express: express/index.md
  - React:
      - React: react/index.md
      - Tanstack Router: react/tanstack/tanstack-router.md
      - Tanstack Form: react/tanstack/tanstack-form.md
      - Tanstack Table: react/tanstack/tanstack-table.md 
      - Tanstack Query: react/tanstack/tanstack-query.md
  - Drizzle: drizzle/index.md 
  - Zod: zod/index.md
  - SQL: sql/index.md
  - PHP: php/index.md
  - Elysia: elysia/index.md
  - Fish-shell: fish-shell/index.md
  - Git: git/index.md
  - MkDocs: mkdocs/index.md
  - Nvim: nvim/index.md
  - Biome: biome/index.md
  - Mermaid: mermaid/index.md
  - PNPM: pnpm/index.md
  - Vite: vite/index.md
  - Biome: biome/index.md
  - Pyhton: python/index.md

